# Generated by Django 5.2.3 on 2025-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=50)),
                ('assists', models.IntegerField(default=0)),
                ('corners_taken', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('dribbles', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DefendingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=50)),
                ('balls_recovered', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('tackles_won', models.IntegerField(default=0)),
                ('clearance_attempted', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=50)),
                ('fouls', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoalkeepingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=50)),
                ('saves', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('saves_from_penalty', models.IntegerField(default=0)),
                ('punches', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=50)),
                ('goals', models.IntegerField(default=0)),
                ('right_foot', models.IntegerField(default=0)),
                ('left_foot', models.IntegerField(default=0)),
                ('headers', models.IntegerField(default=0)),
                ('penalties', models.IntegerField(default=0)),
                ('inside_area', models.IntegerField(default=0)),
                ('outside_areas', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
                ('distance_covered', models.FloatField(default=0.0)),
            ],
        ),
    ]
